create table if not exists users (
    id bigint generated by default as identity primary key,
    slack_team_id varchar(32) not null,
    slack_user_id varchar(32) not null,
    display_name varchar(100) not null,
    email varchar(320),
    avatar_url varchar(1000),
    created_at timestamp with time zone not null,
    last_login_at timestamp with time zone not null
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'uk_users_slack_identity'
          and conrelid = 'users'::regclass
    ) then
        alter table users
            add constraint uk_users_slack_identity
            unique (slack_team_id, slack_user_id);
    end if;
end
$$;
