-- Career DB v6 (docs/erd-v6.dbml · docs/api-spec-v6.md 부록). users 는 V1 에서 만들었다.
--
-- 규칙
-- - enum 은 varchar + CHECK 로 만든다. JPA 의 EnumType.STRING 과 그대로 맞고, 값을 추가할 때 ALTER TYPE 이 필요 없다.
-- - created_at · updated_at 은 엔티티가 Instant.now() 로 채운다(backend-convention 5절). 그래서 DEFAULT 와
--   updated_at 트리거를 두지 않는다. 시드 SQL 은 시각을 직접 넣는다.
-- - 테이블 순서는 FK 방향을 따른다. ai_tasks 가 users · job_postings · job_posting_questions 를 가리키고,
--   experiences · cover_letter_answers 가 ai_tasks 를 가리키므로 ai_tasks 를 그 사이에 둔다.

-- ───────────────────────── 역량 사전 ─────────────────────────

create table competencies (
    id         bigint generated by default as identity primary key,
    name       varchar(100) not null,
    category   varchar(32)  not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_competencies_name unique (name),
    constraint ck_competencies_category
        check (category in ('ROLE', 'TECH', 'SOFT', 'DOMAIN', 'VALUE'))
);

create table competency_aliases (
    id            bigint generated by default as identity primary key,
    competency_id bigint       not null,
    alias         varchar(100) not null,
    created_at    timestamp with time zone not null,
    constraint uk_competency_aliases_alias unique (alias),
    constraint fk_competency_aliases_competency
        foreign key (competency_id) references competencies (id) on delete cascade
);

create index ix_competency_aliases_competency on competency_aliases (competency_id);

-- ───────────────────────── 공고 ─────────────────────────

create table companies (
    id              bigint generated by default as identity primary key,
    name            varchar(200)  not null,
    normalized_name varchar(200)  not null,
    career_url      varchar(1000),
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    constraint uk_companies_normalized_name unique (normalized_name)
);

create table job_postings (
    id          bigint generated by default as identity primary key,
    company_id  bigint        not null,
    position    varchar(200)  not null,
    content     text          not null,
    source_url  varchar(1000),
    deadline    timestamp with time zone not null,
    status      varchar(32)   not null default 'ACTIVE',
    analyzed_at timestamp with time zone,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null,
    constraint uk_job_postings_source_url unique (source_url),
    constraint ck_job_postings_status check (status in ('ACTIVE', 'CLOSED')),
    constraint fk_job_postings_company
        foreign key (company_id) references companies (id) on delete restrict
);

create index ix_job_postings_status_deadline on job_postings (status, deadline);
create index ix_job_postings_company_deadline on job_postings (company_id, deadline);

create table posting_competencies (
    job_posting_id bigint       not null,
    competency_id  bigint       not null,
    weight         decimal(3, 2) not null,
    evidence_line  text         not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    constraint pk_posting_competencies primary key (job_posting_id, competency_id),
    constraint ck_posting_competency_weight check (weight >= 0 and weight <= 1),
    constraint fk_posting_competencies_posting
        foreign key (job_posting_id) references job_postings (id) on delete cascade,
    constraint fk_posting_competencies_competency
        foreign key (competency_id) references competencies (id) on delete restrict
);

create index ix_posting_competencies_competency on posting_competencies (competency_id);

create table job_posting_questions (
    id             bigint generated by default as identity primary key,
    job_posting_id bigint  not null,
    sequence       integer not null,
    prompt_text    text    not null,
    length_limit   integer,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    constraint uk_job_posting_questions_sequence unique (job_posting_id, sequence),
    constraint ck_posting_question_sequence check (sequence > 0),
    constraint ck_posting_question_length_limit check (length_limit is null or length_limit > 0),
    constraint fk_job_posting_questions_posting
        foreign key (job_posting_id) references job_postings (id) on delete cascade
);

-- ───────────────────────── AI 작업 ─────────────────────────

create table ai_tasks (
    id              bigint generated by default as identity primary key,
    task_type       varchar(32)  not null,
    status          varchar(32)  not null default 'PENDING',
    user_id         bigint,
    job_posting_id  bigint,
    question_id     bigint,
    idempotency_key varchar(128) not null,
    input_hash      varchar(64)  not null,
    model           varchar(100),
    prompt_version  varchar(50),
    request_payload jsonb        not null,
    result_payload  jsonb,
    retry_count     integer      not null default 0,
    attempts        jsonb        not null default '[]',
    error_code      varchar(100),
    error_message   text,
    created_at      timestamp with time zone not null,
    started_at      timestamp with time zone,
    completed_at    timestamp with time zone,
    constraint uk_ai_tasks_idempotency_key unique (idempotency_key),
    constraint ck_ai_tasks_type
        check (task_type in ('POSTING_ANALYSIS', 'EXPERIENCE_INTAKE', 'MATCH', 'DRAFT')),
    constraint ck_ai_tasks_status
        check (status in ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    constraint ck_ai_task_targets check (
        (task_type = 'POSTING_ANALYSIS'  and job_posting_id is not null) or
        (task_type = 'EXPERIENCE_INTAKE' and user_id is not null) or
        (task_type = 'MATCH'             and user_id is not null and job_posting_id is not null) or
        (task_type = 'DRAFT'             and user_id is not null and question_id is not null)
    ),
    constraint ck_ai_task_retry check (retry_count >= 0),
    constraint ck_ai_task_timestamps check (
        (status = 'PENDING' and started_at is null     and completed_at is null) or
        (status = 'RUNNING' and started_at is not null and completed_at is null) or
        (status in ('COMPLETED', 'FAILED') and started_at is not null and completed_at is not null)
    ),
    constraint fk_ai_tasks_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_ai_tasks_posting
        foreign key (job_posting_id) references job_postings (id) on delete cascade,
    constraint fk_ai_tasks_question
        foreign key (question_id) references job_posting_questions (id) on delete cascade
);

create index ix_ai_tasks_status_created on ai_tasks (status, created_at);
create index ix_ai_tasks_type_user_status on ai_tasks (task_type, user_id, status);
create index ix_ai_tasks_type_posting_status on ai_tasks (task_type, job_posting_id, status);

-- 같은 대상에 진행 중 작업은 1개. MATCH 는 제외하고 input_hash 로 검증한다.
create unique index uq_ai_task_draft_inflight
    on ai_tasks (user_id, question_id)
    where task_type = 'DRAFT' and status in ('PENDING', 'RUNNING');

create unique index uq_ai_task_intake_inflight
    on ai_tasks (user_id)
    where task_type = 'EXPERIENCE_INTAKE' and status in ('PENDING', 'RUNNING');

create unique index uq_ai_task_analysis_inflight
    on ai_tasks (job_posting_id)
    where task_type = 'POSTING_ANALYSIS' and status in ('PENDING', 'RUNNING');

-- ───────────────────────── 경험 ─────────────────────────

create table experiences (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null,
    title      varchar(200) not null,
    category   varchar(32)  not null,
    start_date date,
    end_date   date,
    situation  text,
    task       text,
    action     text,
    result     text         not null,
    ai_task_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint ck_experiences_category check (category in (
        'TEAM_PROJECT', 'PERSONAL_PROJECT', 'PRACTICE_PROJECT',
        'EXTERNAL_ACTIVITY', 'EMPLOYMENT', 'AWARD_CERTIFICATE'
    )),
    constraint ck_experience_period
        check (start_date is null or end_date is null or end_date >= start_date),
    constraint fk_experiences_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_experiences_ai_task
        foreign key (ai_task_id) references ai_tasks (id) on delete set null
);

create index ix_experiences_user_start on experiences (user_id, start_date);

create table experience_competencies (
    experience_id bigint        not null,
    competency_id bigint        not null,
    strength      decimal(3, 2) not null default 0.70,
    created_at    timestamp with time zone not null,
    constraint pk_experience_competencies primary key (experience_id, competency_id),
    constraint ck_experience_competency_strength check (strength >= 0 and strength <= 1),
    constraint fk_experience_competencies_experience
        foreign key (experience_id) references experiences (id) on delete cascade,
    constraint fk_experience_competencies_competency
        foreign key (competency_id) references competencies (id) on delete restrict
);

create index ix_experience_competencies_competency on experience_competencies (competency_id);

-- ───────────────────────── 사용자 × 공고 ─────────────────────────

create table bookmarks (
    user_id        bigint not null,
    job_posting_id bigint not null,
    created_at     timestamp with time zone not null,
    constraint pk_bookmarks primary key (user_id, job_posting_id),
    constraint fk_bookmarks_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_bookmarks_posting
        foreign key (job_posting_id) references job_postings (id) on delete cascade
);

create table job_matches (
    id             bigint generated by default as identity primary key,
    user_id        bigint        not null,
    job_posting_id bigint        not null,
    match_score    decimal(4, 3) not null,
    verdict        varchar(32)   not null,
    covered_count  integer       not null,
    coverage       jsonb         not null,
    input_hash     varchar(64)   not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    constraint uk_job_matches_user_posting unique (user_id, job_posting_id),
    constraint ck_job_matches_verdict check (verdict in ('RECOMMEND', 'CONDITIONAL', 'HOLD')),
    constraint ck_job_match_score check (match_score >= 0 and match_score <= 1),
    constraint ck_job_match_covered check (covered_count >= 0),
    constraint fk_job_matches_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_job_matches_posting
        foreign key (job_posting_id) references job_postings (id) on delete cascade
);

-- 매칭순 목록: (user_id, match_score desc) 로 훑고 INCLUDE 컬럼만으로 카드를 채운다.
create index ix_job_matches_user_score
    on job_matches (user_id, match_score desc)
    include (job_posting_id, verdict, covered_count);

-- ───────────────────────── 자기소개서 ─────────────────────────

create table cover_letter_answers (
    id                  bigint generated by default as identity primary key,
    user_id             bigint   not null,
    question_id         bigint   not null,
    content             text     not null,
    char_count          integer  not null default 0,
    used_experience_ids bigint[] not null default '{}',
    ai_task_id          bigint,
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null,
    constraint uk_cover_letter_answers_user_question unique (user_id, question_id),
    constraint ck_answer_char_count check (char_count >= 0),
    constraint fk_cover_letter_answers_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_cover_letter_answers_question
        foreign key (question_id) references job_posting_questions (id) on delete restrict,
    constraint fk_cover_letter_answers_ai_task
        foreign key (ai_task_id) references ai_tasks (id) on delete set null
);

create index ix_cover_letter_answers_question on cover_letter_answers (question_id);

-- 경험 목록의 "N개 문항에 사용" 배지: unnest(used_experience_ids) group by 가 이 인덱스를 탄다.
create index ix_answers_used_experiences
    on cover_letter_answers using gin (used_experience_ids);
